# Simulation Parameters
voxel_size: 0.2

# Paths
input_directory: "./data"
output_directory: "./output"

# Fuel Layers and Bulk Densities (Must be in same order)
fuel_layers:
  - filename: "grass_crop.las"
    bulk_density: 0.8
  - filename: "shrub.las"
    bulk_density: 0.8
  - filename: "wood_crop.las"
    bulk_density: 0.8
  - filename: "leaf_crop.las"
    bulk_density: 0.4
  - filename: "leaf_crop_high.las"
    bulk_density: 0.4